# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr: none

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: ms-devlabs.vsts-developer-tools-build-tasks.tfx-installer-build-task.TfxInstaller@2
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.6.x'

- task: ms-devlabs.vsts-developer-tools-build-tasks.package-extension-build-task.PackageAzureDevOpsExtension@2
  displayName: 'Package Extension: OPC.PowerApps.BuildTools'
  inputs:
    patternManifest: '**\extensionManifest.json'
    updateTasksVersion: true
    extensionVisibility: private
    extensionPricing: free